In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\Ryan\anaconda3\envs\pyp\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()
df_salary.head()
df_salary['inflammed'] = df_salary['salary_year_avg']*1.03
df_salary[['salary_year_avg', 'inflammed']]

        salary_year_avg  inflammed
28             109500.0  112785.00
77             140000.0  144200.00
92             120000.0  123600.00
100            228222.0  235068.66
109             89000.0   91670.00
...                 ...        ...
785624         139216.0  143392.48
785641         150000.0  154500.00
785648         221875.0  228531.25
785682         157500.0  162225.00
785692         157500.0  162225.00

[22003 rows x 2 columns]

In [3]:
df_salary['inflammed'] = df_salary['salary_year_avg'].apply(lambda salary: salary*1.03)
df_salary[['salary_year_avg', 'inflammed']]

        salary_year_avg  inflammed
28             109500.0  112785.00
77             140000.0  144200.00
92             120000.0  123600.00
100            228222.0  235068.66
109             89000.0   91670.00
...                 ...        ...
785624         139216.0  143392.48
785641         150000.0  154500.00
785648         221875.0  228531.25
785682         157500.0  162225.00
785692         157500.0  162225.00

[22003 rows x 2 columns]

In [4]:
def projected(salary):
    return salary*1.03
df_salary['inflammed'] = df_salary['salary_year_avg'].apply(projected)
df_salary[['salary_year_avg', 'inflammed']]

        salary_year_avg  inflammed
28             109500.0  112785.00
77             140000.0  144200.00
92             120000.0  123600.00
100            228222.0  235068.66
109             89000.0   91670.00
...                 ...        ...
785624         139216.0  143392.48
785641         150000.0  154500.00
785648         221875.0  228531.25
785682         157500.0  162225.00
785692         157500.0  162225.00

[22003 rows x 2 columns]

In [5]:
import ast
def clean_skills(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)

In [6]:
""" df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list) """

" df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list) "

In [7]:
df['job_skills']

0                                                       NaN
1         ['r', 'python', 'sql', 'nosql', 'power bi', 't...
2         ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
3         ['python', 'c++', 'java', 'matlab', 'aws', 'te...
4         ['bash', 'python', 'oracle', 'aws', 'ansible',...
                                ...
785736    ['bash', 'python', 'perl', 'linux', 'unix', 'k...
785737                       ['sas', 'sas', 'sql', 'excel']
785738                              ['powerpoint', 'excel']
785739    ['python', 'go', 'nosql', 'sql', 'mongo', 'she...
785740                                      ['aws', 'flow']
Name: job_skills, Length: 785741, dtype: str

In [8]:
""" import ast
def clean_skills(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)
df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list) """

" import ast\ndef clean_skills(skill_list):\n    if pd.notna(skill_list):\n        return ast.literal_eval(skill_list)\ndf['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list) "

In [12]:
help(df.apply)

Help on method apply in module pandas.core.frame:

apply(func: 'AggFuncType', axis: 'Axis' = 0, raw: 'bool' = False, result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None, args=(), by_row: "Literal[False, 'compat']" = 'compat', engine: "Callable | None | Literal['python', 'numba']" = None, engine_kwargs: 'dict[str, bool] | None' = None, **kwargs) method of pandas.DataFrame instance
    Apply a function along an axis of the DataFrame.

    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument. The return type of the applied
    function is inferred based on the first computed result obtained after
    applying the function to a Series object.

    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:

        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.

    raw : bool, default False
        Determines if row or column is passed as a Series or ndarray object:

        * ``False`` : passes each row or column as a Series to the
          function.
        * ``True`` : the passed function will receive ndarray objects
          instead.
          If you are just applying a NumPy reduction function this will
          achieve much better performance.

     .. note::

            When ``raw=True``, the result dtype is inferred from the **first**
            returned value.

    result_type : {'expand', 'reduce', 'broadcast', None}, default None
        These only act when ``axis=1`` (columns):

        * 'expand' : list-like results will be turned into columns.
        * 'reduce' : returns a Series if possible rather than expanding
          list-like results. This is the opposite of 'expand'.
        * 'broadcast' : results will be broadcast to the original shape
          of the DataFrame, the original index and columns will be
          retained.

        The default behaviour (None) depends on the return value of the
        applied function: list-like results will be returned as a Series
        of those. However if the apply function returns a Series these
        are expanded to columns.
    args : tuple
        Positional arguments to pass to `func` in addition to the
        array/series.
    by_row : False or "compat", default "compat"
        Only has an effect when ``func`` is a listlike or dictlike of funcs
        and the func isn't a string.
        If "compat", will if possible first translate the func into pandas
        methods (e.g. ``Series().apply(np.sum)`` will be translated to
        ``Series().sum()``). If that doesn't work, will try call to apply again with
        ``by_row=True`` and if that fails, will call apply again with
        ``by_row=False`` (backward compatible).
        If False, the funcs will be passed the whole Series at once.

        .. versionadded:: 2.1.0

    engine : decorator or {'python', 'numba'}, optional
        Choose the execution engine to use. If not provided the function
        will be executed by the regular Python interpreter.

        Other options include JIT compilers such Numba and Bodo, which in some
        cases can speed up the execution. To use an executor you can provide
        the decorators ``numba.jit``, ``numba.njit`` or ``bodo.jit``. You can
        also provide the decorator with parameters, like ``numba.jit(nogit=True)``.

        Not all functions can be executed with all execution engines. In general,
        JIT compilers will require type stability in the function (no variable
        should change data type during the execution). And not all pandas and
        NumPy APIs are supported. Check the engine documentation [1]_ and [2]_
        for limitations.

        .. warning::

            String parameters will stop being supported in a future pandas version.

        .. versionadded:: 2.2.0

    engine_kwargs : dict
        Pass keyword arguments to the engine.
        This is currently only used by the numba engine,
        see the documentation for the engine argument for more information.

    **kwargs
        Additional keyword arguments to pass as keywords arguments to
        `func`.

    Returns
    -------
    Series or DataFrame
        Result of applying ``func`` along the given axis of the
        DataFrame.

    See Also
    --------
    DataFrame.map: For elementwise operations.
    DataFrame.aggregate: Only perform aggregating type operations.
    DataFrame.transform: Only perform transforming type operations.

    Notes
    -----
    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    References
    ----------
    .. [1] `Numba documentation
            <https://numba.readthedocs.io/en/stable/index.html>`_
    .. [2] `Bodo documentation
            <https://docs.bodo.ai/latest/>`/

    Examples
    --------
    >>> df = pd.DataFrame([[4, 9]] * 3, columns=["A", "B"])
    >>> df
       A  B
    0  4  9
    1  4  9
    2  4  9

    Using a numpy universal function (in this case the same as
    ``np.sqrt(df)``):

    >>> df.apply(np.sqrt)
         A    B
    0  2.0  3.0
    1  2.0  3.0
    2  2.0  3.0

    Using a reducing function on either axis

    >>> df.apply(np.sum, axis=0)
    A    12
    B    27
    dtype: int64

    >>> df.apply(np.sum, axis=1)
    0    13
    1    13
    2    13
    dtype: int64

    Returning a list-like will result in a Series

    >>> df.apply(lambda x: [1, 2], axis=1)
    0    [1, 2]
    1    [1, 2]
    2    [1, 2]
    dtype: object

    Passing ``result_type='expand'`` will expand list-like results
    to columns of a Dataframe

    >>> df.apply(lambda x: [1, 2], axis=1, result_type="expand")
       0  1
    0  1  2
    1  1  2
    2  1  2

    Returning a Series inside the function is similar to passing
    ``result_type='expand'``. The resulting column names
    will be the Series index.

    >>> df.apply(lambda x: pd.Series([1, 2], index=["foo", "bar"]), axis=1)
       foo  bar
    0    1    2
    1    1    2
    2    1    2

    Passing ``result_type='broadcast'`` will ensure the same shape
    result, whether list-like or scalar is returned by the function,
    and broadcast it along the axis. The resulting column names will
    be the originals.

    >>> df.apply(lambda x: [1, 2], axis=1, result_type="broadcast")
       A  B
    0  1  2
    1  1  2
    2  1  2

    Advanced users can speed up their code by using a Just-in-time (JIT) compiler
    with ``apply``. The main JIT compilers available for pandas are Numba and Bodo.
    In general, JIT compilation is only possible when the function passed to
    ``apply`` has type stability (variables in the function do not change their
    type during the execution).

    >>> import bodo  # doctest: +SKIP
    >>> df.apply(lambda x: x.A + x.B, axis=1, engine=bodo.jit)  # doctest: +SKIP

    Note that JIT compilation is only recommended for functions that take a
    significant amount of time to run. Fast functions are unlikely to run faster
    with JIT compilation.

In [13]:
df_salary

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,inflammed
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd...",112785.00
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac...",144200.00
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}",123600.00
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr...",235068.66
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro...",91670.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab...",143392.48
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",NaN,NaN,154500.00
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':...",228531.25
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ...",162225.00
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}",162225.00

In [19]:
def salary_projected(row):
    if 'Senior' in row['job_title_short']:
        return row['salary_year_avg'] * 1.05
    else:
        return row['salary_year_avg'] * 1.03
    
df_salary['inflated_salary_projected'] = df_salary.apply(salary_projected, axis=1)
df_salary[['job_title_short', 'salary_year_avg', 'inflated_salary_projected']].head(2)

   job_title_short  salary_year_avg  inflated_salary_projected
28  Data Scientist         109500.0                   112785.0
77   Data Engineer         140000.0                   144200.0

In [20]:
df_salary['inflated_salary_projected'] = df_salary.apply(lambda row: row['salary_year_avg']*1.05 if 'Senior' in row['job_title_short'] else row['salary_year_avg'] * 1.03, axis=1)
df_salary[['job_title_short', 'salary_year_avg', 'inflated_salary_projected']].head(20)

          job_title_short  salary_year_avg  inflated_salary_projected
28         Data Scientist         109500.0                  112785.00
77          Data Engineer         140000.0                  144200.00
92          Data Engineer         120000.0                  123600.00
100        Data Scientist         228222.0                  235068.66
109          Data Analyst          89000.0                   91670.00
116        Data Scientist         114000.0                  117420.00
146         Data Engineer         129500.0                  133385.00
180          Data Analyst          90250.0                   92957.50
212        Data Scientist         157500.0                  162225.00
257        Data Scientist         103128.0                  106221.84
307         Data Engineer         185000.0                  190550.00
339         Data Engineer         195000.0                  200850.00
380         Data Engineer          97500.0                  100425.00
388         Data Engineer          89000.0                   91670.00
410          Data Analyst         133285.0                  137283.55
450        Data Scientist         157500.0                  162225.00
495  Senior Data Engineer         168500.0                  176925.00
520      Business Analyst          63000.0                   64890.00
545         Data Engineer          80000.0                   82400.00
571         Data Engineer         110000.0                  113300.00